"""Render the public matrix from the evidence shipped with the app."""

from pathlib import Path

from .installation import compatibility_catalogue


def render_matrix():
    catalogue = compatibility_catalogue()
    lines = [
        "# Hardware compatibility",
        "",
        "<!-- Generated by python -m ha_growatt.hardware_matrix; edit hardware_evidence.json. -->",
        "",
        f"Evidence checked: {catalogue['checked']}.",
        "",
        catalogue["notice"],
        "",
        "The verified installation contains two inverters. The owner identified one as a",
        "MIN 2500TL-XH; the model-to-feed mapping and datalogger variants still need",
        "confirmation. We cannot yet publish a complete model/firmware combination as",
        "hardware-qualified. Battery controls have no physical qualification here.",
        "",
        "An unlisted model is unverified, not necessarily unsupported. Start with",
        "[the installation guide](guided-setup.md) and leave experimental controls off.",
        "",
        "| Hardware | Evidence | Software or source project |",
        "| --- | --- | --- |",
    ]
    for entry in catalogue["entries"]:
        lines.append(
            f"| [{entry['model']}](#{entry['id']}) | {entry['level']} | {entry['project']} |"
        )
    for entry in catalogue["entries"]:
        lines.extend(["", f'<a id="{entry["id"]}"></a>', "", f"## {entry['model']}", ""])
        for key, label in {
            "level": "Evidence",
            "project": "Software or source project",
            "firmware": "Firmware",
            "datalogger": "Datalogger",
            "connection": "Connection",
            "telemetry": "Readings",
            "controls": "Controls",
            "profile": "Profile guidance",
            "limits": "Limits",
        }.items():
            lines.extend([f"**{label}:** {entry[key]}", ""])
        lines.extend(f"- [{source['label']}]({source['url']})" for source in entry["sources"])
    lines.extend(
        [
            "",
            "## Add or correct evidence",
            "",
            "[Send a hardware report](https://github.com/Herbertmt978/HA-Growatt/issues/new?template=hardware-report.yml).",
            "Include exact model, inverter and datalogger firmware, connection, software version,",
            "profile and what you actually observed. Do not publish serial numbers, credentials",
            "or raw packet captures. Readings, setting readback, write acknowledgement and",
            "physical behaviour are separate results. No setting change is needed to report",
            "working telemetry. A closed issue or passing protocol test alone is not",
            "hardware verification.",
            "",
        ]
    )
    return "\n".join(lines)


if __name__ == "__main__":
    Path("docs/hardware-matrix.md").write_text(render_matrix(), encoding="utf-8")
